### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by kraenhansen** [zooniverse/scribeAPI#1]
I would love for a description on the GitHub project or a descriptive text in the README of the repository.

**Comment by riordan** [comment]
Hi, @kraenhansen. It's been a while. May the 4th be with you, albeit one year later.

This project is sort of the spiritual successor to [Scribe](https://github.com/zooniverse/scribe), the generalized version of the framework built for [Old Weather](http://oldweather.org). It's designed to let a developer and a curator (or scientist) create a crowdsourcing project to turn digitized documents into structured datasets with the help of the public.

It's a joint collaboration between the team at NYPL Labs and Zooniverse, and is kind of a standalone version of Panoptes, but with a focus on structured data transcription and consensus.

But yeah, we should probably put in a better readme (#47)
