### ISSUE TITLE
How will we handle development of multiple simultaneous projects in this repo?

### ISSUE THREAD

**Issue by riordan** [zooniverse/scribeAPI#12]
With NYPL starting on our Emigrant Savings Bank project and New Bedford Whaling happening, how should we handle our different codebases here, while still relying on advancing the API?

**Comment by saschaishikawa** [comment]
Ideally, each project would be specified entirely by it's project.json file, meaning everything else is out-of-box. As I'm working on this, I'm moving everything so each project is dependent only an API call.

**Comment by riordan** [comment]
BUMP - we've pretty much got this figured out, right?
