### ISSUE TITLE
"Done" button within a workflow skips the rest of the workflow

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/scribeAPI#189]
This might be myself and Darren misinterpreting design.

The main action button frequently defaults to a label of "Done" when no option has been selected in a task. If clicked, the workflow punts the user all the way to the end of the workflow asking "Thanks for all your work! Is there anything left to mark?".

Is this intended behavior? I can understand a "skip / bad page" button, but is that what this is intended to accomplish?

**Comment by saschaishikawa** [comment]
Nope, that's not intended behavior. Andrea doesn't have that problem so it's probably specific to the way the mark workflow was written in Whaling.

**Comment by chrissnyder** [comment]
Ah, gotcha, adding the "whaling" tag.
