### ISSUE TITLE
Classifying a mark as "bad"

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/scribeAPI#193]
Is there functionality within the Transcribe workflow if you come across a mark that is incorrect to classify it as such?

**Comment by saschaishikawa** [comment]
There's a "Bad Subject" button on the transcribe tool, but nothing so far to specify that a mark is bad.

**Comment by nonword** [comment]
The "Bad Subject" (not committed to that language) button that appears in the transcribe tool submits a special "flag_bad_subject_task" classification that increments the marking subject's flagged_bad_count by one. After 3 votes (currently hard coded) the mark subject acquires status "bad" which removes it from both workflows.

**Comment by saschaishikawa** [comment]
@nonword Ah, excellent. I didn't realize that any action was performed in response to the flag. Closing this issue since the question was answered.
