### ISSUE TITLE
Make configurable the transcribe option offered in mark and verify phases

### ISSUE THREAD

**Issue by wlla** [zooniverse/scribeAPI#200]
These currently appear in the Mark and Verify phases near the marks.

**Comment by beefoo** [comment]
I'm going to take a stab at this

**Comment by saschaishikawa** [comment]
Can we re-use the `generates_subject_type` defined  in each tool to infer whether or not a transcribe option will be available?

**Comment by saschaishikawa** [comment]
This commit breaks the workflow in the Whaling Logs. Reverting for now. Let's discuss tomorrow.

**Comment by beefoo** [comment]
Sorry about that.  Was the addition of another key in the config the thing that broke your workflow? I am unfamiliar with what `generates_subject_type` does. Does setting that to null in the config do the job here?

**Comment by saschaishikawa** [comment]
@beefoo, the extra key wasn't the problem. When the line in the SubjectViewer 

`allowsTranscribeSubject = @props.task.tool_config.allows_transcribe_subject != false`

executes the first time, `task` is undefined (not sure exactly why, but probably some async thing). Replacing it with 

`allowsTranscribeSubject = @props.task?.tool_config.allows_transcribe_subject != false`

seems to do the trick. However, you might be able to do the same thing by using `generates_subject_type`, which is also defined in the task. This just stores the key for the transcribe subject that gets generated once the mark is saved. We could set a convention that `generates_subject_type = null` and hide the button in those cases.

**Comment by beefoo** [comment]
Ah, thanks @saschaishikawa.  I'll make sure to test on Whaling Logs before I commit the change

**Comment by saschaishikawa** [comment]
@beefoo, @nonword, @simensta, @chrissnyder: let'a all submit PRs instead of committing straight to master. I've definitely broken some things this way myself and since there are quite a few devs on this project I think it makes sense.

**Comment by chrissnyder** [comment]
Seconding this. PRs are (partially) designed to prevent this sort of regression. Having a second pair of eyes on the same piece of code is invaluable for bug catching and just general code quality.
