### ISSUE TITLE
Emigrants: Design homepage

### ISSUE THREAD

**Issue by wlla** [zooniverse/scribeAPI#213]
Add custom design to the Emigrant's homepage.

**Comment by beefoo** [comment]
Very light design work has been done to make the homepage readable, but still need to make it more flashy.

**Comment by wlla** [comment]
Let's mute the background image (maybe 75% transparency?) and add some backing to the section with text to amp up legibility.

**Comment by wlla** [comment]
Redesign placement of NYPL branding
