### ISSUE TITLE
Update Team page to be Team & Organizations

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/scribeAPI#229]
Much of the content has changed from my first draft. The finalized, team-approved content can be found here:

https://docs.google.com/document/d/17dGMjUzfjnG08ePNITIaunpmI_jSk96r9EihkYD52eo/edit#heading=h.3zl9fxn5p452

Thus, the content all needs to be updated, including on the landing page, the team page, and the About page.

Additionally, the site needs an Organizations page, or the Team page needs to become "Team/Organizations" or something along those lines. Organizations are not currently on the site anywhere. The list of organizations has been simplified down to just hyperlinks, because there are so many of them. :-)

Finally, could those pages could get a bit of styling/design and imagery?

**Comment by chrissnyder** [comment]
Let's hold off on doing custom design on the sub pages. Heath is over booked as-is.

That said, Kevin provided some cool random photos for the site, which we can and should sprinkle through the about page. Link below.

https://slack-files.com/T024GDV4T-F090CFY6R-eff8b02179

**Comment by saschaishikawa** [comment]
Are we including a team site?

**Comment by DarrenMcRoy** [comment]
Need to add headshots for the team, and also add the list of organizations from the above Google doc.

https://docs.google.com/document/d/17dGMjUzfjnG08ePNITIaunpmI_jSk96r9EihkYD52eo/edit#heading=h.3zl9fxn5p452

**Comment by trouille** [comment]
Attached are headshots to add to team page. 

![clive_wilkinson](https://cloud.githubusercontent.com/assets/4975655/10090793/2de8719e-62f9-11e5-8e81-3e6db0592e9e.jpg)
![clivewilkinson](https://cloud.githubusercontent.com/assets/4975655/10090794/2de98372-62f9-11e5-8369-a9fa1434177c.jpg)
![gil_compo](https://cloud.githubusercontent.com/assets/4975655/10090795/2de9de30-62f9-11e5-9df8-d9e2b6c7eb0c.jpg)
![gordon_smith](https://cloud.githubusercontent.com/assets/4975655/10090796/2de9f3fc-62f9-11e5-8491-0e9b24fafb1d.jpg)
![kevin_wood](https://cloud.githubusercontent.com/assets/4975655/10090798/2deafb3a-62f9-11e5-9bd5-8d48d79e576c.jpg)
![mark_mollan](https://cloud.githubusercontent.com/assets/4975655/10090797/2deabbb6-62f9-11e5-960f-36313937438d.jpg)
![mark_procknik](https://cloud.githubusercontent.com/assets/4975655/10090799/2df5e7f2-62f9-11e5-80f5-06482a7556d3.jpg)
![michael_lapides](https://cloud.githubusercontent.com/assets/4975655/10090800/2df60b2e-62f9-11e5-8455-f051fda8a2d0.jpg)
![philip_brohan](https://cloud.githubusercontent.com/assets/4975655/10090802/2df8ebdc-62f9-11e5-8255-144ecf4b572a.jpg)
![rob_allan](https://cloud.githubusercontent.com/assets/4975655/10090801/2df66b00-62f9-11e5-8487-c5b8403b4dce.JPG)

**Comment by trouille** [comment]
Also, on the team page, please add:

This project was built by Sascha Ishikawa (Zooniverse - Adler Planetarium) using Scribe [http://scribe.nypl.org], a framework for crowdsourcing the transcription of text-based documents.

**Comment by trouille** [comment]
Images on Team page are now broken. Quick fix? 
Also, still need to add the line mentioned in comment above.
