### ISSUE TITLE
Change styling of text on landing page (home page) to fit

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/scribeAPI#238]
As mentioned by @chrissnyder on #233 -- a separate issue.

The home page looks "cluttered," but in my opinion, that's mostly because the text is too huge and not well-organized. The text that is there has been approved by the science team, and I'm personally very attached to it as a really strong call to action. **It just doesn't need to be so BIG!** :-)

By shrinking it, we should be able to style it as follows:

*Explore the documented adventures of whaling ships in the Arctic.
Discover in their writings new clues about climatology and history.*

And the rest of it can be even smaller, and certainly does not have to be line-spaced so widely:

*Whalers have sought their quarry in perilous Arctic waters for centuries. Their ships’ logbooks contain detailed observations of the often difficult weather and sea-ice conditions they faced, as well as first-hand accounts of all kinds of events. Climate scientists and historians alike have much to learn from these logs—but first they need your help to mark and transcribe them.*

By shrinking the text so that it organizes well (see how small the text is here: http://www.chimpandsee.org/#/ -- yet still perfectly effective!) we should be able to eliminate any sense of "clutter" on that page.

@saschaishikawa mentioned that the styling for that page was intrinsically linked between all Scribe projects, but I don't see why that has to be the case, and why we shouldn't be able to tweak it for what is, really, a custom build. Sascha said he may have found a way to style that text independently?

**Comment by chrissnyder** [comment]
Design is going to be tricky between the projects because they are all built on the same codebase. It's not-too-dissimilar a problem from PFE, where we can't style those projects individually, but just provide hooks, like the background image to change.

That said, I heard movement towards a per-project CSS file for Scribe, so that might be a solved problem over here.

**Comment by chrissnyder** [comment]
Looks to be better this morning. Still might need some tweaking, but can tackle that after the beta.

@heathv thoughts?

**Comment by saschaishikawa** [comment]
@chrissnyder, project-specific styles in the corresponding `style.css` takes precedence over Scribe defaults

**Comment by DarrenMcRoy** [comment]
Having the tagline in all-caps looks odd to me, when the project title itself isn't. Is that changeable? @heathv agree?

**Comment by saschaishikawa** [comment]
It's changeable. Let me know when a decision has been made.

**Comment by DarrenMcRoy** [comment]
The landing page now looks good to me except that there appears to be no maximum width on the description which can theoretically lead to some slightly absurd-looking design:

![screen shot 2015-09-01 at 3 05 06 pm](https://cloud.githubusercontent.com/assets/8987864/9614983/eaf36ec0-50ba-11e5-96f6-3770a19051be.png)

Could we set a max width on it, a la Gorongosa? It looks so much neater:

![screen shot 2015-09-01 at 3 07 13 pm](https://cloud.githubusercontent.com/assets/8987864/9615010/17c1f890-50bb-11e5-9345-fa001738cbe5.png)

Otherwise, this could be closed.
