### ISSUE TITLE
Metadata options/formatting on a group page

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/scribeAPI#243]
For example: http://whalinglogs.herokuapp.com/#/groups/55ce58536634610003410000

Kevin sent more information to be placed on the group page. Before I reply, how flexible are we in what we can output on that page? Would like to know so I can frame the discussion appropriately.

**Comment by saschaishikawa** [comment]
@chrissnyder, style-wise we're pretty flexible. In terms of content, there's a rake task that imports data/metadata from `groups.csv`. At the moment, the data fields for a group can be the following:

* key
* name
* description
* cover_image_url
* external_url
* meta_data_1
* retire_count

It shouldn't be too difficult, in theory, to modify this to add/remove fields; however, for the beta launch we should probably stick to what's currently supported.

**Comment by chrissnyder** [comment]
Oh for sure, I'm not proposing anything additional for the beta. Merely trying to figure out what's possible in the future and for launch
