### ISSUE TITLE
Create Tutorial

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/scribeAPI#257]
It should show a sequence of informational slides to new users and users who have not logged in.

**Comment by DarrenMcRoy** [comment]
I have written draft text for this - one three-slide tutorial for Mark, one for Transcribe.

Could revisit, tweak, and expand.

**Comment by DarrenMcRoy** [comment]
Holding on this until workflow is close to finalized. @saschaishikawa and @simensta -- let me know when you feel that OW:W and ANZAC, respectively, are in a final enough form to have a final tutorial drafted!

**Comment by DarrenMcRoy** [comment]
Draft text is now available: https://docs.google.com/document/d/1h3_URjwrf_imM_cDJ1Xp7iy8Y_sL8n5k-MwdSbkFpqs/edit#

Will finalize once everything else is finalized.

What do we want to do for images? Gif screengrabs of each process?

**Comment by simensta** [comment]
Thank you, @DarrenMcRoy. Gifs would be a nice addition.

**Comment by DarrenMcRoy** [comment]
Heath taught me how to do that. I'll have to figure out exactly what process should be .gif-ed for each, but yes, that should work.
