### ISSUE TITLE
In Mark Workflow, Add "Transcribe This Page Now" Button

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/scribeAPI#278]
All part of addressing the comments that there lacked a continuity to keep up with the narrative of the logbooks.

**Comment by DarrenMcRoy** [comment]
Quick question: if you "transcribe this page now," what happens when you finish? Do you go back to marking the next page?

**Comment by saschaishikawa** [comment]
You just go back to the same mark page that sent you into “Transcribe”

**Comment by DarrenMcRoy** [comment]
I guess that works. Then is there just one button they could press to move on?

I'm thinking in terms of the workflow:
- mark everything
- click "transcribe this page"
- transcribe the page
- return to the marking and... click a button to move to marking the next page?

Also, when you transcribe, are you only transcribing your marks on the page? Or everyone's marks?

**Comment by saschaishikawa** [comment]
> On Aug 25, 2015, at 12:58 PM, DarrenMcRoy <notifications@github.com> wrote:
> 
> I guess that works. Then is there just one button they could press to move on?
> 
> I'm thinking in terms of the workflow:
> 
> mark everything
> click "transcribe this page"
> transcribe the page
> return to the marking and... click a button to move to marking the next page?
That’s correct.
> Also, when you transcribe, are you only transcribing your marks on the page? Or everyone's marks?
> 
> 

They’ll be transcribing everyone’s marks on that particular page.
