### ISSUE TITLE
Domain-restricted Typekit should not be required (or should be un-domain-restricted)

### ISSUE THREAD

**Issue by nonword** [zooniverse/scribeAPI#279]
Currently we require ProximaNova, which is loaded through typekit, which currently has a finite number of whitelisted domains. We either need to remove domain restriction from typekit or remove ProximaNova and typekit as requirements. Premium fonts should be included in a project-specific styles.css or project-specific javascript (which would require supporting project-specific js).

**Comment by beefoo** [comment]
I'd vote for the latter option (remove typekit as requirements) or use Google Fonts for generic Scribe projects. Having all Scribe projects rely on one Typekit account makes me nervous even if we can whitelist all domains.

Project-specific js would be great as well regardless.  I created a separate issue (#281) for this and will take a stab at it.
