### ISSUE TITLE
Allow Users to "Delete" Marks

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/scribeAPI#292]
Implement some code to allow users to locally remove marks from their interface. These marks aren't removed from the database, but rather hidden from that specific user. However, if enough users click the "delete" button, we can retire the mark and *actually* delete it from the db.

NOTE: similar to the code that implements hiding marks that have already been transcribed by a user

**Comment by DarrenMcRoy** [comment]
> However, if enough users click the "delete" button, we can retire the mark and actually delete it from the db.

Why not have deleting a mark be the same functionally as marking one as "bad?"
