### ISSUE TITLE
Content after New Line in TextArea Ignored

### ISSUE THREAD

**Issue by simensta** [zooniverse/scribeAPI#301]

**Comment by nonword** [comment]
May need more instruction after all. I don't think I'm replicating the issue. I switched to Anzac and selected History Sheet > Next of Kin and then transcribed the field in the resulting textarea tool in the Transcribe workflow. The resulting classification showed this:
```
       ...
	"annotation" : {
		"value" : "this is line 1\nthis is line 2\nline 3\nline 4\nline 5"
	}, ...
```

And the generated subject was:
```
       ...
	"data" : {
		"values" : [
			{
				"value" : "this is line 1\nthis is line 2\nline 3\nline 4\nline 5"
			}
		],
		"task_prompt" : "Transcribe **next-of-kin**. Press [Shift] + [Enter] to start a new line."
	}, ...
```
Tried this in FF, Safari, and Chrome. Seems to me newlines are being encoded correctly. Where is you see text being ignored?
