### ISSUE TITLE
Mark: Delete/Transcribe buttons not accessible at edges of document

### ISSUE THREAD

**Issue by nonword** [zooniverse/scribeAPI#345]
When creating a mark and dragging it to the extreme right or bottom of an image, the Transcribe and Delete buttons can no longer be accessed. There may be a solution in modifying the getDeleteButtonPosition and getMarkButtonPosition methods to check for this scenario and adjust the coordinates computed to keep the icons in view.

**Comment by simensta** [comment]
related to issue #328.
