### ISSUE TITLE
Top 20 ships to include in launch page + photos

### ISSUE THREAD

**Issue by trouille** [zooniverse/scribeAPI#363]
Here's the list of the top 20 to include in main page for the launch. Chosen because among the easier logbooks to read and many have images (choice by Kevin & Michael):

For those marked as not having an image, please use the the image attached here called:
icon_ship.jpg (not the one you're currently using).  

Cut pages Kevin has listed should correspond to the image number, not any printed page numbers in the logs. 

The metadata for all ships except for ODHS 938B Progress is found by: http://www.whalingmuseum.org/explore/library/logbooks-journals  > view logbook > click here for description > http://www.whalingmuseum.org/explore/library/logbooks/congress-kwm_55 (for example)
Some urls have /digitized-logbook-shipname-refnum and others only /shipname-refnum.

KWM 370  Betsey Williams (no image) - cut starting at pp 310-311, 20 Apr 1854
KWM 180 Saratoga - have image - no cut
KWM 74 Eliza Adams - have image - no cut
KWM 55  Congress (no image) - no cut
ODHS 7 Seneca (no image) - cut starting at pp 182-182, 14 Sep 1871
KWM 192  Trident (no image) - cut starting at pp 100-101, 14 Nov 1870
ODHS 948A Grampus - have image - no cut 
ODHS 948B Grampus - have image 2 - cut starting at pp 102-103, 12 Nov 1889
ODHS 950 Newport  - have image - cut starting at pp 334-335, after Hershel Island baseball records    
ODHS 951 Beluga - have image - no cut
KWM 104 Horatio - have image -  cut starting at pp 66-67, 31 Oct 1896 (Remainder filled in with unrelated personal diary.)
ODHS 955 William Baylies - have image - cut starting at pp 98-99, 3 Nov 1905
ODHS 956A William Baylies - have image 2 - no cut
ODHS 958 Herman - have image - cut starting at pp 78-79, 2 Nov 1910 
ODHS 959 Herman - reuse image - cut starting at pp 106-107, 10 Nov 1911
Helen Snow - have image - cut starting at pp 56-57, 21 Aug 1872
John Wells - have image - cut starting at pp 84-85, 14 Nov 1871
Mary D. Hume - have image -  cut starting at pp 268-269, 30 Sep 1892
Milo - have image - no cut
Rosario - have image - no cut

Leave these 2 for the next round:
ODHS 956B William Baylies - reuse image from ODHS 956B William Baylies -  cut starting at pp 100-101, 7 Nov 1907
ODHS 938B Progress - have image - no cut

![grampus_2](https://cloud.githubusercontent.com/assets/4975655/9990501/8c0a4182-6027-11e5-9b35-155f096a67d4.jpg)
![william_baylies_2](https://cloud.githubusercontent.com/assets/4975655/9990504/936802d4-6027-11e5-9298-a309100eecd9.jpg)
![icon_ship](https://cloud.githubusercontent.com/assets/4975655/9990505/97533846-6027-11e5-9456-6258657ffb06.jpg)
![beluga_odhs951](https://cloud.githubusercontent.com/assets/4975655/9923475/f0b3df82-5cba-11e5-988e-50b2444b9ba2.jpg)
![eliza_adams_kwm74](https://cloud.githubusercontent.com/assets/4975655/9923471/f0b2eb72-5cba-11e5-9e1e-2ae7a3b07cbf.jpg)
![grampus_odhs948](https://cloud.githubusercontent.com/assets/4975655/9923470/f0afbda8-5cba-11e5-941e-91b8dd044ce1.jpg)
![helen_snow_odhs_6](https://cloud.githubusercontent.com/assets/4975655/9923473/f0b391bc-5cba-11e5-8568-718422232264.jpg)
![herman_odhs958](https://cloud.githubusercontent.com/assets/4975655/9923474/f0b3b1ce-5cba-11e5-9a6f-5dce5a261623.jpg)
![horatio_kwm104](https://cloud.githubusercontent.com/assets/4975655/9923472/f0b2ed2a-5cba-11e5-86ba-edbeee2c3e3e.jpg)
![john_wells_leftmost_ship_odhs_769](https://cloud.githubusercontent.com/assets/4975655/9923476/f0bc339e-5cba-11e5-9e5b-4e6940f596f6.jpg)
![mary_d_hume_odhs_949](https://cloud.githubusercontent.com/assets/4975655/9923478/f0be13e4-5cba-11e5-8388-89bc829d8365.jpg)
![milo_rightmost_odhs_147](https://cloud.githubusercontent.com/assets/4975655/9923477/f0bd0c06-5cba-11e5-8aa5-491aeb514b00.jpg)
![newport_odhs_950](https://cloud.githubusercontent.com/assets/4975655/9923480/f0c04f1a-5cba-11e5-9e48-5b78eca4c827.jpg)
![progress_odhs_938b](https://cloud.githubusercontent.com/assets/4975655/9923479/f0bf3cd8-5cba-11e5-82b2-aed18f2144a9.jpg)
![rosario_odhs_654b](https://cloud.githubusercontent.com/assets/4975655/9923481/f0c0f730-5cba-11e5-8e41-9be31210a554.jpg)
![saratoga_kwm180](https://cloud.githubusercontent.com/assets/4975655/9923482/f0c792ac-5cba-11e5-9707-cbcb45f2ba73.jpg)

**Comment by saschaishikawa** [comment]
@trouille, there's an A and B logbook for Grampus (ODHS 948), William Baylies (ODHS 956), and Milo (KWM 351). Are there specific ones I should choose from? Should I include both?

**Comment by trouille** [comment]
When there are A and B logbooks, we do want to include both in the full data set the community will eventually see. From what Kevin has written, these are separate logbooks. This means you'll definitely want to include the 'A' or 'B' designation so it's clear they're two separate logbooks. 

For our Top 20, I believe the Grampus A and B is the only pair we've included in the list. And, for example, we only include William Baylies ODHS 956A (and not B) in the Top 20 list.

**Comment by saschaishikawa** [comment]
@trouille do you have the original copies of the ship images? Their filenames have been replaced with gibberish and is impossible to tell the ships apart.

**Comment by trouille** [comment]
Yes, will email.
