### ISSUE TITLE
Locally Transcribed Marks Are Still Re-Transcribable

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/scribeAPI#376]

**Comment by trouille** [comment]
Related to this:
Volunteer working in both Firefox and Chrome. 
Gets the first page (https://static.zooniverse.org/whaling-data.oldweather.org/subjects/journalofsaratog00unse_0001.jpg) I say:
  Date - no, next
  Location/position - no, next
  Mentions of sea ice - no, next
  Descriptions of the weather - no, next
  Additional items - done
  Anything left to mark - no, next page
Then I click the "OW" icon to go back to the home page. 
I select Saratoga, marking.
I get the same page again.
I have now done this same page about five times.
