### ISSUE TITLE
Talk post by Janet Jaguar - link isn't clickable

### ISSUE THREAD

**Issue by trouille** [zooniverse/scribeAPI#395]
https://www.zooniverse.org/projects/zooniverse/old-weather/talk/116/8589/  Janet Jaguar's post providing the link to the oldWeather forum - the link to 'old Weather forum' shows up as blue, but isn't clickable.

**Comment by DarrenMcRoy** [comment]
Looks like locking a thread makes the links unclickable.

Also greys stuff out, which makes it a bit harder to read.

There are many use-cases for locking threads that involves wanting to keep them easily readable. We should change both of those things, I think... and @trouille, I think this is @aweiksnar territory, not @saschaishikawa ? :-)

**Comment by aweiksnar** [comment]
@saschaishikawa Just send you a PR on PFE that should settle this
