### ISSUE TITLE
"Start a discussion about this logbook" seems to not link properly

### ISSUE THREAD

**Issue by trouille** [zooniverse/scribeAPI#396]
When I click on "Start a discussion about this logbook", it takes me to, for example, https://www.zooniverse.org/projects/zooniverse/old-weather/talk/subjects/967263/  but there's nothing there - no box to input text into or copy of the logbook page or anything. 

If I click on the Talk tab from the link above, that takes me to https://www.zooniverse.org/projects/zooniverse/old-weather/talk/ where there are discussion boards, etc. as expected.

**Comment by saschaishikawa** [comment]
@trouille I see the comment box when I scroll all the way down

**Comment by saschaishikawa** [comment]
Ah, I just realized this is related to the login issue. You need to be logged in to see them

**Comment by DarrenMcRoy** [comment]
Should non-logged-in users get a prompt, then?

**Comment by saschaishikawa** [comment]
Nevermind. Some permissions weren't set correctly on Panoptes. This should be resolved now. Closing.
