### ISSUE TITLE
Post-Soft Launch Fixes

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/scribeAPI#397]
- [x] add "Talk" tab to top navbar (priority) resolves #394 
- [x] add link to Old Weather Classic (priority)
- [x] 'select all sea-ice descriptions that apply' step is not box-enabled
- [x] improve layout/design of ship info page
- [x] improve layout/design of teams and about page
- [x] add team photos to page

**Comment by simensta** [comment]
@saschaishikawa: see PR#398 for item add "Talk" tab to top navbar
