### ISSUE TITLE
Mobile Alert

### ISSUE THREAD

**Issue by wlla** [zooniverse/scribeAPI#433]
Spec out popup for mobile/tablet users notifying them that the site is a desktop app. Something like:

"Welcome! Thanks for your interest in NYPL's Emigrant Savings Bank Project. The site is an app designed for desktops. For the full experience, come back later from your laptop or desktop."

Unless there's a standard way of handling these sorts of alerts.

**Comment by beefoo** [comment]
Resolved: https://github.com/zooniverse/scribeAPI/pull/492
