### ISSUE TITLE
Tool counter updating for tools

### ISSUE THREAD

**Issue by tufixm** [zooniverse/scribeAPI#461]
In my mark file I have the following tool config:
```
"tool_config": {
        "options":[
          {"type": "rectangleTool", "label": "Red Rectangles", "color": "red", "generates_subject_type": "rectangle"},
          {"type": "rectangleTool", "label": "Green Rectangles", "color": "green", "generates_subject_type": "rectangle"},
          {"type": "rectangleTool", "label": "Blue Rectangles", "color": "blue", "generates_subject_type": "rectangle"}
        ]
    }
```
If I select and draw a rectangle (for example, a red one), then all the other rectangles get their counters updated.
However, if I change the `generates_subject_type` field to, say, `red_rectangle`, `green_rectangle` and `blue_rectangle`, then their respective counters are updated separately.

Was the implementation of that counter meant to be synced to the generated subject type, instead of the tool itself? Personally, I find it a bit counter-intuitive, especially in my case, in which I do care about the type of marking (red, green, blue), but the subsequent transcription will be the same for all rectangles, regardless of their colour.

**Comment by nonword** [comment]
Working on merging a possible fix for this.

**Comment by nonword** [comment]
Should be fixed as of https://github.com/zooniverse/scribeAPI/pull/465
