### ISSUE TITLE
Two "Eliza Adams 1863" icons and two "Congress 1864" on the home page

### ISSUE THREAD

**Issue by trouille** [zooniverse/scribeAPI#559]
This may be very simple (just need to remove the duplicates) or it may be a bit more complicated if it has to do with how new ships are loaded when ships are retired (i.e., classifications complete).

**Comment by saschaishikawa** [comment]
The dupes seem to result from the `project:load` rake task not completing (e.g. due to some error). This isn't a big deal other than the dupe can't be accessed. Might have to go into the database manually to delete.
