### ISSUE TITLE
'Bad page' Button  

### ISSUE THREAD

**Issue by VVH** [zooniverse/scribeAPI#72]

**Comment by simensta** [comment]
We are still in the process of determining what this button should ask user to observe. Some possibilities:
* _Mark Workflow_: Allows a volunteer to indicate a poor quality root subject (e.g., blurry image). 
* _Transcribe Workflow_: Allows a volunteer to indicate an correctly marked, but illegible mark-subject.
* _Transcribe Workflow_: Allows a volunteer to indicate an incorrectly marked mark-subject (e.g., incorrect region of the root subject).
