### ISSUE TITLE
[MEGA] Core Tools

### ISSUE THREAD

**Issue by riordan** [zooniverse/scribeAPI#82]
Buncha Tools!

- Marking
 - [x] Point #83
 - [x] Rectangle #84
 - [x] Text Rows #85
- Transcribe
 - [x] Text #86
 - [x] Number #87
 - [x] Date #88
 - [x] Composite #89

**Comment by saschaishikawa** [comment]
I think we can close this, even though we don't have number and date tools yet. Thoughts? @simensta @nonword

**Comment by simensta** [comment]
I think we should wait to close the issue until we incorporate the number and date tools/configurations.
